@extends('layouts.dashboard-sidenav')
@section('title','Purchase Page')
@section('content')
    @include('components.back-end.Purchase.purchase-list')
    @include('components.back-end.Purchase.purchase-create')
    @include('components.back-end.Supplier.supplier-create')
    @include('components.back-end.Supplier.supplier-update')
    @include('components.back-end.Product.product-create')
    @include('components.back-end.Product.product-update')
    @include('components.back-end.Product.product-delete')
    @include('components.back-end.Purchase.purchase-due-print')
    @include('components.back-end.Purchase.purchase-update')
    @include('components.back-end.Purchase.purchase-delete')
@endsection
